name: 'Di hola'
description: 'Saluda desde Docker python.'
inputs:
  nombre:
    required: false
    type: string
    default: John Doe
    description: "Tu nombre para el saludo"
outputs:
	saludo:
		description: Te saludamos por tu nombre
runs:
  using: 'docker'
  image: 'Dockerfile' # 'docker://debian:stretch-slim', si quisieramos apuntar a una imagen de dockerhub
  args:
    - ${{ inputs.nombre }}